### PR TITLE
fusell: Fix SIGINT handling

### PR DESCRIPTION
**Pull request by nirs**
Python default SIGINT handler was preventing the fuse SIGINT handler
from triggering, causing SIGINT to be ignored when using fusell.py
module. When fule_session_loop() returned, a KeyboardInterrupt was
raised, leaving around the mount.

Using same signal handling as in fuse.py fixes this issue.

### CODE REVIEW

**Comment by nirs** [comment]
Ping

**Comment by nirs** [comment]
Is this project still maintained here?

**Comment by earonesty** [comment]
I've found that this and other issued have mostly been merged in here: https://github.com/billziss-gh/fusepy/blob/windows/fuse.py

**Comment by nirs** [comment]
@earonesty thanks!

**Pull request merged**
